spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.159.128/employees
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.nehs.antares.entity


## 日志配置
logging:
  config: src/main/resources/logback.xml
  file:
    path: ${user.dir}/logs/antares
  level:
    com.nehs.antares.mapper: debug