spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.159.128/employees
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.nehs.antares.entity